### ISSUE TITLE
Incorrect Interface typed used in code generation

### ISSUE THREAD

**Issue by Siegrift** [ethereum-ts/TypeChain#369] opened 2021-04-07 15:31 UTC
Hi,

I have generated TS types for my [smart contracts](https://github.com/api3dao/airnode/tree/master/packages/protocol/contracts) , however there are TS errors in the types generated. I have debugged the issue and found that if I change the generated code from:

```ts
interface AirnodeRrpInterface extends ethers.utils.Interface {
...
}
```

to

```ts
import { Interface } from "@ethersproject/abi";

interface AirnodeRrpInterface extends Interface {
...
}
```

there are no more type errors.

I am using:
- TS verson `4.1.2`
- "@typechain/ethers-v5": "^6.0.5"
- "typechain": "^4.0.3"

And I am executing this command: `yarn typechain --target ethers-v5 --outDir ./src/types './artifacts/contracts/**/!(*.dbg).json'` (the contracts in the path are autogenerated). 

P.S. Thanks for this library :)

**Comment by krzkaczor** [comment] 2021-04-07 19:22
Thanks for this issue. Clearly seems like a bug on our part. I will try to get it fixed this week.

**Comment by krzkaczor** [comment] 2021-04-24 22:38
I am having problems trying to reproduce it. Can you create a repository with minimal reproducible example?

**Comment by Siegrift** [comment] 2021-04-25 11:03
Hi, you can find it (not) working in our project: https://github.com/api3dao/airnode/tree/master/packages/protocol

Files generated by typechain are gitignored and I am using grep to correct the imports https://github.com/api3dao/airnode/blob/master/packages/protocol/package.json#L10

Maybe the problem is on my end, but not sure where.

**Comment by davidtperk** [comment] 2021-05-19 19:51
Experiencing the same bug.
```
{
  "@typechain/ethers-v5": "^7.0.0", 
  "typechain": "^5.0.0",
  "typescript": "^4.1.5"
}
```

**Comment by krzkaczor** [comment] 2021-05-19 20:18
Can you prepare minimal reproducible example @davidtperk? (repo or something?) 

It really takes me a lot of time to dive into a big project and try to realize what's triggering a bug. Thanks!

**Comment by davidtperk** [comment] 2021-05-19 21:28
@krzkaczor it looks like my `yarn.lock` fell out of sync with `package.json`, creating some dependency conflicts. Deleted it, re-ran `yarn`, and working smoothly now. Thanks.

**Comment by krzkaczor** [comment] 2021-05-19 21:39
I am gonna close it for now. Please reopen with minimal repro.

**Closed by krzkaczor** 2021-05-19 21:39 UTC
Labels: bug
