### ISSUE TITLE
Add target for ethers v5

### ISSUE THREAD

**Issue by HenryNguyen5** [ethereum-ts/TypeChain#205] opened 2020-01-16 16:39 UTC
I haven't gotten a good look at how v5 has changed in terms of typing, but I think additional work would be needed to support v5 as a target. It's in beta right now so no rush, but would like to get it on the roadmap :)

**Comment by krzkaczor** [comment] 2020-01-21 21:47
@HenryNguyen5 I just released `@typechain/truffle-v5`. Make sure to update core package to load `@typechain` namespaced packages...

Can u help me to understand whats missing for full support? Providing a link to a public repo using `truffle@5` would be super useful for tests

**Comment by HenryNguyen5** [comment] 2020-01-21 21:48
Hey @krzkaczor, this issue is for ethers, not truffle. Im not aware of any public repos using it yet, but i could take a look around and let you know. I dont think its a pressing issue

**Comment by krzkaczor** [comment] 2020-01-22 11:09
@HenryNguyen5 oh 🤦‍♂ Nevermind.

**Comment by jurosh** [comment] 2020-04-21 12:44
Seems it's recommended to use v5 for new projects, so def would be nice to have TypeChain ready too.

There are two visible issues and required steps to make it work:

1. update to provider import like

```
import { ..., providers } from 'ethers';
...
signerOrProvider: Signer | providers.Provider
```

2. contract cast to specific type not working so needed to type-cast through `any`

```
new Contract(address, _abi, signerOrProvider)  as any as ExchangeContract
```
- I was not investigating this, but def something what should be fixed proper way


Otherwise seems generated code is working fine...

**Comment by PaulRBerg** [comment] 2020-06-02 21:24
> Seems it's recommended to use v5 for new projects, so def would be nice to have TypeChain ready too.

I can confirm that this is the case. Richard is just playing it ultra safe - v5 has been ready to ship for a long time.

**Comment by pcowgill** [comment] 2020-06-03 21:41
Yep. Buidler and Waffle both recently went through the effort of preparing for ethers v5, so I think the timing is good to start work on this.

**Comment by krzkaczor** [comment] 2020-06-19 11:46
It looks like @zemse is cooking something :-> 

https://github.com/zemse/TypeChain/tree/master/packages/target-ethers-v5

**Comment by zemse** [comment] 2020-06-20 22:05
Hi guys, can you please have a look at PR #250 and try it out?

**Comment by krzkaczor** [comment] 2020-06-30 20:11
It's published as `@typechain/ethers-v5`, still in beta.

**Comment by adrianmcli** [comment] 2020-07-01 19:28
Excited to see this come out of beta.

**Comment by krzkaczor** [comment] 2020-08-06 09:02
It was released as stable!

**Closed by krzkaczor** 2020-08-06 09:02 UTC
