### ISSUE TITLE
Wrap event return type in a separate type variable so it can be re-used outside of typings file

### ISSUE THREAD

**Issue by lazarmitic** [ethereum-ts/TypeChain#454] opened 2021-08-16 07:15 UTC
Currently when typed events are generated return type is defined inline, for example:
```
Deposited(
  depositor?: null,
  recipient?: null,
  yieldTokenAmount?: null,
  shareAmounts?: null,
  rate?: null,
): TypedEventFilter<
  [string, string, BigNumber, BigNumber, BigNumber],
  {
    depositor: string;
    recipient: string;
    yieldTokenAmount: BigNumber;
    shareAmounts: BigNumber;
    rate: BigNumber;
  }
>;
```

My suggestion is to define a separate type variable for the event, like this:
```
export type DepositedEventType = 
  [string, string, BigNumber, BigNumber, BigNumber] & {
    depositor: string;
    recipient: string;
    yieldTokenAmount: BigNumber;
    shareAmounts: BigNumber;
    rate: BigNumber;
  };
```

And then use it like this:
```
Deposited(
  depositor?: null,
  recipient?: null,
  yieldTokenAmount?: null,
  shareAmounts?: null,
  rate?: null,
): TypedEventFilter<DepositedEventType>;
```

This way if I need to define a variable in my code that stores event data, I can use `DepositedEventType` generated inside typeings file, instead of redefining it in my code manually every time I update contract ABI.

**Comment by krzkaczor** [comment] 2021-08-16 12:32
It's a good idea. We will be working soon on this. Duplicate of: https://github.com/ethereum-ts/TypeChain/issues/440

**Closed by krzkaczor** 2021-08-16 12:32 UTC
