### ISSUE TITLE
Correct way to type contract models (structs, events, ...)

### ISSUE THREAD

**Issue by StErMi** [ethereum-ts/TypeChain#442] opened 2021-08-04 06:09 UTC
Hi there, maybe I missed something but which should be the correct way to type my custom contract's events, structs, and errors?

For example, in my Solidity contract I've some custom structs returned by my contract's method and events. I would expect that Typechain when I create typings also create interfaces for those structs and events with the same name of the struct and events so when I use a typed contract on my web3 app I don't need to recreate those interfaces but they are directly exported by the Typechain types.

am I missing something, it's not supported yet or will not be supported?

**Comment by krzkaczor** [comment] 2021-08-12 19:56
Duplicate of: https://github.com/ethereum-ts/TypeChain/issues/440

**Closed by krzkaczor** 2021-08-12 19:56 UTC
