### ISSUE TITLE
typechain generates .ts binging only for the first contract

### ISSUE THREAD

**Issue by MikkySnow** [ethereum-ts/TypeChain#111] opened 2018-10-12 09:08 UTC
I've configured truffle.js and tsconfig.json as described in the tutorial and installed all dependencies, but typechain still generates bindings only for first file found in the build directory.

I've tried to use truffle-typechain-example and put my contracts there, but I faced with the same error

**Comment by lsaether** [comment] 2018-10-17 19:35
Hey @MikkySnow I had the same problem. The problem is that the README in the `truffle-typechain-example` incorrectly leaves off the quotes around the argument to the `typechain` CLI. If you have the quotes around the argument to the CLI it should work.

Please see https://github.com/ethereum-ts/truffle-typechain-example/pull/1 for the fix.

**Comment by krzkaczor** [comment] 2018-10-20 17:34
Thanks for this issue @MikkySnow and thanks for providing the fix @lsaether. It's merged! 

Funny thing is that I even mentioned the problem with quotes in Typechain's readme only to forget about it later 😆

**Closed by krzkaczor** 2018-10-20 17:34 UTC
