### ISSUE TITLE
Generated types are broken; wrongly extends @ethersproject/Contract

### ISSUE THREAD

**Issue by gbarros** [ethereum-ts/TypeChain#288] opened 2020-10-27 13:38 UTC
I've been upgrading my project from buidler to hardhat and with it all its plugins. However. I've found what seems to be an issue with typechain (which is invoked by they hardhat-typechain plugin).  I've tried using typechain cli directly and the error is still reproducible. 

The generated typescript type definition files seem to be using a different version of the  @ethersproject/Contract API because the editor points out the incompatibility of the extended class. Here is an example:

```javascript
...
export class BitsManipulationLibrary extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: BitsManipulationLibraryInterface;

  functions: {
    int32SignExtension(
...
```
and if you follow the implementation of the Contract it is extending : 

```javascript
...
export declare class Contract {
    readonly address: string;
    readonly interface: Interface;
    readonly signer: Signer;
    readonly provider: Provider;
...
```

After I remove all the `interface:  XYZInterface` instances on the generated files, I get one more error for the usage of different `Contract` origins, and fixing it manually, both types of errors, is enough to make tests to run again. 

This second error comes from the generated code: 
```javascript
import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { WorkerManager } from "./WorkerManager";

export class WorkerManagerFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): WorkerManager {
    return new Contract(address, _abi, signerOrProvider) as WorkerManager;
  }
}
```
in which this last line errors with: 
```
Conversion of type 'Contract' to type 'WorkerManager' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type 'Contract' is missing the following properties from type 'WorkerManager': addListener, acceptJob, "acceptJob()", cancelHire, and 19 more.ts(2352)
```

Changing the import is enough to fix it, as such:
```javascript
import { Signer } from "ethers";
import { Provider } from "@ethersproject/providers";
import { Contract } from "@ethersproject/contracts";
```

## Versions:
```
- nodeJS: v12.18.3
- typechain: 3.0.0

- @nomiclabs/hardhat-ethers: 2.0.0
- @nomiclabs/hardhat-waffle: 2.0.0
- @typechain/ethers-v5: 2.0.0
- ethereum-waffle: 3.1.2
- ethers: 5.0.19
- hardhat: 2.0.2
- ts-generator: 0.1.1
- ts-node: 9.0.0
- typescript: 4.0.3
- hardhat-typechain: 0.3.3
```

**Comment by tuler** [comment] 2020-10-27 15:08
I can confirm that updating this project `ethers` dependency from [5.0.2](https://github.com/ethereum-ts/TypeChain/blob/93b7ca2c26c9f947f0b41e62577fbdbca4739cab/packages/target-ethers-v5/package.json#L66) to latest `5.0.19` breaks the generated code.

**Comment by krzkaczor** [comment] 2020-10-28 09:40
Thanks, guys I will look into this. 

Btw. I realized that ethers shouldn't be `dependency` for target package at all (only a peer dep).

**Comment by gbarros** [comment] 2020-10-28 12:59
So we found out that deleting the previous yarn.lock and running yarn again solved the issue. Maybe we can close this issue.

**Comment by krzkaczor** [comment] 2020-11-04 20:58
This was probably due to a mistake in `target-ethers-v5` which had explicit dependency on ethers. Now we have example using newest ethers and everything works fine.

Released as new major version of target.
https://github.com/ethereum-ts/TypeChain/releases/tag/v4

**Closed by krzkaczor** 2020-11-04 20:58 UTC
