### ISSUE TITLE
export abi and bytecode

### ISSUE THREAD

**Issue by pkieltyka** [ethereum-ts/TypeChain#356] opened 2021-03-17 13:01 UTC
I've been using and loving typechain/ethers-v5 in my projects -- thanks for making it and maintaining it well.

A few times I've had the use-case to access a contract abi and bytecode directly, ie. for debugging a payload for instance. I would reach into an artifact or another generated piece of content for it. However, since I already have the gen'd typechain interface, and the X__factory files already have `const _abi` and `const _bytecode`, can we just rename+export those as `export const abi` and `export const bytecode` ..?

Point is, I think we should export them instead of leaving them as an internal type for completeness and usefulness.

**Comment by quezak** [comment] 2021-03-17 13:48
Thanks for the idea, we'll think of that - closing as duplicate of #344

**Closed by quezak** 2021-03-17 13:48 UTC
